Update main.yml
adding simulating error in yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,7 +11,10 @@ jobs:
 
    - name: Run a simple github action
      run: echo "this workflow run successfully for this particular action"
-   
+
+   - name: Simulate Error
+     run: echo"Error simulated"; exit 1
+    
    
  
  
